from pymongo import MongoClient
import os

DB_NAME = 'proDB'
DB_NAME_CRAWLER = 'crawlerDB'
ip = '127.0.0.1'
#ip = '35.154.116.6' #Public IP for repupro Instance
# ip = '52.66.167.52'

port=27017
DATABASE = MongoClient(ip,port)[DB_NAME]
DATABASE_CRAWLER = MongoClient(ip,port)[DB_NAME_CRAWLER]


REGISTEREDUSERS_COLLECTION = DATABASE.registeredUsers
HOTEL_COLLECTION = DATABASE.hotelData
RESTAURANT_COLLECTION = DATABASE.restaurantData
SOCIALMEDIADATA_COLLECTION = DATABASE.socialMediaData
TICKET_COLLECTION = DATABASE.ticketData
REPLYCREDENTIALS_COLLECTION = DATABASE.replyLoginCredentials
ZOMATO_ENTITYID_COLLECTION = DATABASE.zmEntityId
DEPTHOTEL_COLLECTION = DATABASE.departmentHeadsHotel
DEPTRESTAURANT_COLLECTION = DATABASE.departmentHeadsRestaurant
SAVEDEMAILDATA_COLLECTION = DATABASE.savedEmailData
SMSDATA_COLLECTION = DATABASE.smsData
REPLIES_COLLECTION = DATABASE.replies

COUNTRY_COLLECTION = DATABASE_CRAWLER.countries
STATE_COLLECTION = DATABASE_CRAWLER.states
CITY_COLLECTION = DATABASE_CRAWLER.city
AREAS_COLLECTION = DATABASE_CRAWLER.area
SOURCES_COLLECTION = DATABASE_CRAWLER.sources
PROPERTY_COLLECTION = DATABASE_CRAWLER.properties
SEQUENCE_COLLECTION = DATABASE_CRAWLER.seqs

DATA_DIR = os.getcwd()+'/data'
